services:
  - type: web
    name: coinnexus
    env: node
    plan: free
    buildCommand: node build.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: NEWS_API_KEY
        value: your_news_api_key_here
    healthCheckPath: /api/health
    autoDeploy: true
